language: php

sudo: false

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
    - export SYMFONY_PHPUNIT_VERSION=6.0
    - composer install --no-progress --no-suggest --ansi

script:
    - vendor/bin/simple-phpunit --verbose
